version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senhaprojeto
      MYSQL_DATABASE: projetoGames
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -psenhaprojeto || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

  app:
    build: ./backend/backendProjeto
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/projetoGames
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: senhaprojeto
      JWT_SECRET: 7A2B4C6E8F0A1B3D5E7F9A0B2C4D6E8F0A1B3D5E7F9A0B2C4D6E8F0A1B3D5E7F9
    depends_on:
       db:
        condition: service_healthy

volumes:
  mysql_data: